Feature/web3 auth integration
Nuxify/sophon pull request #16
Opened 2023-05-25 10:03 UTC by JosesGabriel

2023-05-29 09:17 UTC, kabaluyot commented on lib/internal/string_constants.dart
move to .env

WEB3AUTH_APP_BUNDLE_ID=
WEB3AUTH_APP_URL_SCHEME=

2023-05-29 09:17 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_cubit.dart
>    final DeployedContract greeterContract;
group by modifiers

final ...
final ...
late ...
late ...

2023-05-29 09:17 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_cubit.dart
> +    } else if (loginType == LoginType.google) {
loginType (=> provider) should be:

- metaMask
- web3Auth

google provider or other social/email providers are all under web3auth provider

2023-05-29 09:17 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_cubit.dart
>      fetchGreetingTimer =
remove na goro nato ning fetch-interval related diri kols? Introduce nalang ta pull to refresh ..

most likely dapps via websocket or manual refresh for data

2023-05-29 09:17 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_cubit.dart
> +  Future<void> initializeGoogleProvider() async {
should be initializeWeb3AuthProvider

All social logins supported by web3auth at the end, will be invoking this

2023-05-29 09:17 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_cubit.dart
> +      if (type == LoginType.metaMask) {
use switch

2023-05-29 09:17 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_cubit.dart
> +  Future<void> sendTransaction({
remove this and add logic Transaction.callContract direct to 'updateGreeting'

2023-05-29 09:17 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_cubit.dart
> +  Future<void> initializeGoogleProvider() async {
Where is it invoked?

2023-05-29 09:17 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_state.dart
> +class InitializeGoogleProviderLoading extends Web3State {}
InitializeWeb3AuthProviderLoading ... etc

2023-05-29 09:17 UTC, kabaluyot commented on lib/module/auth/service/cubit/auth_state.dart
> +class LoginWithGoogleLoading extends AuthState {}
LoginWithWeb3AuthGoogleSuccess

need separate vs tradiiton login with google

2023-05-29 09:17 UTC, kabaluyot commented on lib/internal/web3_utils.dart
> +Uint8List bigIntToBytes(BigInt value, int length) {
move eip 191 and eip 712 signature related to

web3_eip191.dart
web3_eip171.dart

2023-05-29 09:17 UTC, kabaluyot commented on lib/internal/web3_utils.dart
> +  Uint8List result = Uint8List(length);
Can we add eip191 and eip712 features in separate PR?

2023-06-05 04:11 UTC, JosesGabriel commented on lib/infrastructures/service/cubit/web3_cubit.dart
>      fetchGreetingTimer =
Remove nalang nato ni pag mag implement na ta ug websocket? Dili sakto butangan ug pull to refresh if ani ang UI man gud. @kabaluyot 
![image](https://github.com/Nuxify/Sophon/assets/36292417/22a5343e-92ac-494f-a255-89438b0e5b39)

2023-06-05 04:17 UTC, JosesGabriel commented on lib/infrastructures/service/cubit/web3_cubit.dart
> +  Future<void> initializeGoogleProvider() async {
`home_screen.dart`

2023-06-05 09:13 UTC, kabaluyot commented on lib/infrastructures/service/cubit/web3_cubit.dart
>      fetchGreetingTimer =
Shet karon ra nako nabasa my bad naka push nako sa removed periodic fetch greeting. Cge ra kols bahalag for internal use ra si pull to refresh for greeting para ma kita lang ang updated text without reopening ang app 

cc @JosesGabriel

2023-06-06 02:25 UTC, kabaluyot requested changes
- [ ] pull to refresh for fetch greetings
- [ ] fix unit tests
- [ ] fix widget tests
- [ ] QA in playstore internal build

2023-06-06 07:26 UTC, kabaluyot approved these changes

2023-06-06 07:27 UTC, merged